const actionTypes ={
    SET_MOVIES:"SET_MOVIES",
    SET_MOVIES_LOADING:"SET_MOVIES_LOADING",
    SET_GENRES_LOADING:"SET_GENRES_LOADING",
    SET_MOVIES_ERROR:"SET_MOVIES_ERROR",
    SET_GENRES_ERROR:"SET_GENRES_ERROR",
    SET_ERROR:"SET_ERROR",
    SET_GENRES: "SET_GENRES"

}

export default actionTypes